### PR TITLE
fix encoding

### PR DESCRIPTION
**Pull request by DirtyRacer1337**

### CODE REVIEW

**Comment by Grokitach** [comment]
Aaaah edited the file in GitHub on mobile and it fucked the encoding. Your fix doesn't seem to fix anything, or does it ?

**Comment by DirtyRacer1337** [comment]
You probably can edit eng files, cause utf8 encoding ASCII compatible

**Comment by DirtyRacer1337** [comment]
@Grokitach bump

plus additional info, I was right and GH had warning about it
изображение

**Comment by Grokitach** [comment]
Thanks a lot ! :) I will need to propagate this to the dev2 branch as well

**Comment by DirtyRacer1337** [comment]
need help with that?

**Pull request merged**
