### PR TITLE
Momopate's Detailed Weapon Stats + Mag Redux ru_RU translation

### PR DESCRIPTION
**Pull request by CV514**
It just works.

изображение

### CODE REVIEW

**Comment by CV514** [comment]
Also added missing Mags Redux and Ammo Check translations. 
изображение

**Comment by CV514** [comment]
And little consistency fix for Russian strings for G.A.M.M.A. Close Quarter Combat with removal "BaS" from ammo labels (English strings are all set).

**Comment by CV514** [comment]
And last one for that batch, New Coffee DLTX translation. It's better to brew some ground coffee with proper properties, not st_ground_coffee with st_ground_coffee_descr. Already sent same files to mod author but it may be faster to include here.

**Comment by Grokitach** [comment]
Thank you very much !

**Pull request merged**
